# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Java 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
        
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json

        # lint
        # unit test

      - name: Gradle Assemble Debug & Release APK
        run: ./gradlew assemble

      - name: Gradle Assemble Debug & Release App Bundle
        run: ./gradlew bundle

      - name: Archive Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/outputs/apk/debug/app-debug.apk

      - name: Archive Unsigned Release APK
        uses: actions/upload-artifact@v2
        with:
          name: unsigned-release-apk
          path: app/outputs/apk/release/app-release-unsigned.apk

      - name: Archive Debug App Bundle
        uses: actions/upload-artifact@v2
        with:
          name: debug-aab
          path: app/outputs/bundle/debug/app-debug.aab

      - name: Archive Release App Bundle
        uses: actions/upload-artifact@v2
        with:
          name: release-aab
          path: app/outputs/bundle/debug/app-release.aab
